# Research Paper: Brain Tumor Detection

### Libraries
```{r eval=T, message=F}
#import libraries
library(vegan)
library(survival)
library(bnlearn)
library(dplyr)
library(ggplot2)
library(lattice)
library(mice)
library(tableone)
library(caret)
library(rpart)
library(e1071)
```
  
### Reading the Features.csv Image Processing Output File
```{r eval=T, message=T}
# reading an old one actually to directly study results
data <- read.csv("features.csv")
data
# Combine truth position 3 (insular) and 4 (parietal) due to the small size of the 
# insular cortex and their close position in brain
data$truePosition <- ifelse(data$truePosition==4, 3 , data$truePosition)
data$truePosition <- as.factor(data$truePosition)
# Remoce Ids to avoid overfitting
data <- data[-c(which( colnames(data)=="id"))]
```


### Splitting Data into Train and Test Set
```{r eval=T, message=F}
#dataTrain = data[seq(1,nrow(data),2),]
#dataTest = data[seq(2,nrow(data),2),]
dataTrain = data[seq(1,25,1),]
dataTest = data[seq(26,nrow(data),1),]
```

### Application of ML Algorithms
```{r eval=T, message=T}

############## Naive Bayes   ##############

nb = naiveBayes(truePosition ~ . , dataTrain)
preds = predict(nb, dataTest)
bayesAccuracy <- sum(predict(nb, dataTest)==dataTest$truePosition) / nrow(dataTest)

############## Decision Tree ##############

tree <- rpart(truePosition~ .,
             data=dataTrain,
             method="class")
dtAccuracy <- (sum(predict(tree, dataTest, type="class")==dataTest$truePosition)) / nrow(dataTest)

```

### Accuracy Comparison
```{r eval=T, message=T}
############## Accuracy comparison  ##############
n <- nrow(dataTest)
dtAccuracyInCI <-  toString(dtAccuracy)
bayesAccuracyInCI <- toString(bayesAccuracy)
accuracyComparisonMatrix <- matrix(c(dtAccuracyInCI,bayesAccuracyInCI),ncol=2,byrow=TRUE)
colnames(accuracyComparisonMatrix) <- c("Decision Tree", "Naive Bayes")
rownames(accuracyComparisonMatrix) <- c("Accuracy")
accuracyComparisonTable <- as.table(accuracyComparisonMatrix)
accuracyComparisonTable
```
